//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrometheusMini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignments_174852
    {
        public int HomeWorkId { get; set; }
        public int TeacherId { get; set; }
        public int CourseId { get; set; }
    
        public virtual Courses_174852 Courses_174852 { get; set; }
        public virtual Homework_174852 Homework_174852 { get; set; }
        public virtual Teachers_174852 Teachers_174852 { get; set; }
    }
}
