//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrometheusMini.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment_174852
    {
        public Nullable<int> CourseId { get; set; }
        public int StudentId { get; set; }
    
        public virtual Courses_174852 Courses_174852 { get; set; }
        public virtual Student_174852 Student_174852 { get; set; }
    }
}
