//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrometheusMini.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Training_20Feb_MumbaiEntity : DbContext
    {
        public Training_20Feb_MumbaiEntity()
            : base("name=Training_20Feb_MumbaiEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assignments_174852> Assignments_174852 { get; set; }
        public virtual DbSet<Courses_174852> Courses_174852 { get; set; }
        public virtual DbSet<Enrollment_174852> Enrollment_174852 { get; set; }
        public virtual DbSet<Homework_174852> Homework_174852 { get; set; }
        public virtual DbSet<Planning_174852> Planning_174852 { get; set; }
        public virtual DbSet<Student_174852> Student_174852 { get; set; }
        public virtual DbSet<Teachers_174852> Teachers_174852 { get; set; }
        public virtual DbSet<Teaches_174852> Teaches_174852 { get; set; }
    }
}
