//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrometheusMini.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text.RegularExpressions;

    public class StuCustomValidator : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            if (value != null)
            {
                string password = value.ToString();

                if (Regex.IsMatch(password, @"^[A-Z][a-z]*"))
                {
                    return ValidationResult.Success;
                }
                else
                {
                    return new ValidationResult("Password must starts with Capital Letter");
                }
            }
            else
            {
                return new ValidationResult("" + validationContext.DisplayName + " is required");
            }
        }
    }

    public partial class Student_174852
    {
        public int StudentId { get; set; }
        [Required(ErrorMessage = "Username cannot be null")]
        public string Username { get; set; }
        [Required(ErrorMessage = "FName cannot be null")]
        public string FName { get; set; }
        [Required(ErrorMessage = "LName cannot be null")]
        public string LName { get; set; }
        [Required(ErrorMessage = "Address cannot be null")]
        public string Address { get; set; }
        [Required(ErrorMessage = "DOB cannot be null")]
        public System.DateTime DOB { get; set; }
        [Required(ErrorMessage = "City cannot be null")]
        public string City { get; set; }
        [Required(ErrorMessage = "Password cannot be null", AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        [StringLength(25, ErrorMessage = "Password should have atleast 8 characters", MinimumLength = 8)]
        [RegularExpression(@"(\S)+", ErrorMessage = " Space not allowed")]
        [StuCustomValidator]
        public string Password { get; set; }
        [Required(ErrorMessage = "MobileNo cannot be null")]
        [StringLength(10, ErrorMessage = "Mobile Number nust be 10 characters", MinimumLength = 10)]
        public string MobileNo { get; set; }
    
        public virtual Enrollment_174852 Enrollment_174852 { get; set; }
        public virtual Planning_174852 Planning_174852 { get; set; }
    }
}

